[project]
name = "llm-eval-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.12.0",
    "datasets>=4.4.1",
    "lm-eval>=0.4.9.2",
    "transformers>=4.45.0",
]
